//Get Movie Names API 
GET http://localhost:3000/movies/

###
//Update New Movie API 
POST http://localhost:3000/movies/ 

### 
// Get Movie Based on MovieId 
GET http://localhost:3000/movies/:movieId/

### 
//Updates the details of a movie in the movie table based on the movie ID API 
PUT http://localhost:3000/movies/:movieId/

### 
// Deletes a movie from the movie table based on the movie ID API 
DELETE http://localhost:3000/movies/:movieId/